### ISSUE TITLE
listdb fails

### ISSUE THREAD

**Issue by dstndstn** [astro-datalab/datalab#24]
Welcome to the Data Lab, dstndstn

```
> datalab listdb
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dl/dltasks.py", line 1040, in run
    res = queryClient.list (token=token, table=self.table.value)
  File "/usr/local/lib/python3.8/site-packages/dl/Util.py", line 82, in __call__
    return function(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/dl/queryClient.py", line 934, in list
    return qc_client.mydb_list (token=def_token(token), table=table)
  File "/usr/local/lib/python3.8/site-packages/dl/Util.py", line 80, in __call__
    return function(self.obj, *args, **kw)
TypeError: mydb_list() got multiple values for argument 'token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/datalab", line 169, in <module>
    resp = task.run()
  File "/usr/local/lib/python3.8/site-packages/dl/dltasks.py", line 1042, in run
    print ("Error listing MyDB tables: " % str(e))
TypeError: not all arguments converted during string formatting
```

**Comment by rnikutta** [comment]
Hi Dustin, which version of datalab are you running? (datalab -v)
listdb (and mydb_list) do work for me....

If the package is old (current is 2.18.9), please update first with:

pip install --ignore-installed --no-cache-dir noaodatalab

**Comment by dstndstn** [comment]
> datalab -v
Task Version:  2.18.9

**Comment by dstndstn** [comment]
I also have a helpdesk conversation open -- not using the command-line client, but suggesting (?) that there's something weird in my mydb?  Maybe?  I don't really understand what is being said there.
https://datalab.noao.edu/help/index.php?qa=684&qa_1=having-trouble-fetching-ls8_photoz-results-ls8_tractor-result

**Comment by lijuan** [comment]
Please use 
'datalab mydb_list'
instead

**Comment by chaduhduh** [comment]
Closing this due to no activity. Please submit a new issue if the problem reoccurs.
